# Generated by Django 3.2.6 on 2021-09-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='track_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
