# Generated by Django 3.2.6 on 2021-10-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_label_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
