# Generated by Django 3.2.8 on 2021-10-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_has_formats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='track_list',
            new_name='track_list1',
        ),
        migrations.AddField(
            model_name='product',
            name='track_list2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='track_list3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='track_list4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
